### ISSUE TITLE
Code Style Rules

### ISSUE THREAD

**Issue by RavenX8** [RavenX8/osIROSE-new#15]
I have decided to require a coding style. We will be enforcing [Google's coding style](http://google.github.io/styleguide/cppguide.html) to ensure all code created is easy for someone new to the project to understand by being consistent.

**Comment by RavenX8** [comment]
2c61b5151bde6f6c53888ad1abb97316f1095774

**Comment by shid0x** [comment]
Pretty cool, that way new people can get around easily,it was a bit of a clusterfuck before.

**Comment by RavenX8** [comment]
Yes it was! I want to avoid that happening again.

**Comment by L3nn0x** [comment]
I don't agree with the part about only passing const references as arguments and using pointers to output data. Ex : void Foo(const string &in, string *out);

I think this construction is more error prone because it means that out may not be valid at the time Foo is called (nullptr or wrong address). I'd rather use a reference for the output variable as well as it provides a bit more safety over the validity of the variable.

**Comment by RavenX8** [comment]
I would prefer the pointer because I rather have the function check to see if we care about the output instead if it doing work and wasting memory on something we don't care about.
